public enum Treetype {

	ROOT, MODULE, MCALL, FUNCTION, FCALL, PARAMLIST, PARAM, IF, FOR, INTFOR, ASSIGN /* not the assign() {} block; that's a BLOCK */, OP, IDENT, VECTOR, INDEX, FLIT, SLIT, INCLUDE, USE, DISPMODE, CONDITION, RANGE, NOP;

}
